ALTER TABLE `tuote`
	ADD COLUMN `myyntikate` DECIMAL(10,0) NOT NULL DEFAULT '0',
	ADD COLUMN `katelaskenta` CHAR(8) NOT NULL DEFAULT '0' COMMENT 'm,y,n',
	ADD COLUMN `hintamuutospvm` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
